# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b670b3f3cdd2a3c85cd9e97c98e1039958dd7415e77abeef94f4253ffc2f9ce3b599375e3aef940c3b0c05db0c1daaa879dc514883f19b1fc655bbd4d3175b25

test:
  secret_key_base: d341b2c817b5d8f1f919c560b119e58b7fb8ba9a569760bd12fc059b3f96696720fa134276c5613f4601c8c7cb415090327cc26440978b412594c4996e1b45f7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
